version: "3"

services:
  api_server:
    build: ./backend
    ports:
      - "443:8000"
    depends_on:
      - redis
    restart: always

  web:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api_server
    restart: always
  
  redis:
    image: redis:4-alpine
    volumes:
      - "${PWD}/backup/redis-data/:/data"
    command: redis-server --appendonly yes
    restart: always


volumes:
  redis-data:
