# Generated by Django 2.0.3 on 2018-04-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180330_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_label', models.CharField(max_length=20)),
                ('team_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='handle',
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='game',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='teacher',
            field=models.CharField(max_length=20),
        ),
    ]
