# Generated by Django 2.0.3 on 2018-04-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180405_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
