# Generated by Django 2.0.3 on 2018-04-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20180413_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
