# Generated by Django 2.0.3 on 2018-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20180422_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msgtype',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
