# Generated by Django 2.0.3 on 2018-04-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='team',
        ),
    ]
