# Generated by Django 2.0.3 on 2018-06-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20180521_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='房間名稱', max_length=100),
        ),
    ]
