# Generated by Django 2.0.3 on 2018-06-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='game',
        ),
        migrations.AddField(
            model_name='room',
            name='gameId',
            field=models.CharField(default='', max_length=100),
        ),
    ]
